export const CHANGE_CURRENT_ALBUM = 'album/CHANGE_CURRENT_ALBUM';
export const CHANGE_IS_LOADING = 'album/CHANGE_IS_LOADING';
export const CHANGE_IS_PULLDOWN_LOADING = 'album/CHANGE_IS_PULLDOWN_LOADING';